// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define RGBLIGHT_DEFAULT_HUE 128
#define RGBLIGHT_DEFAULT_SAT 255
#define RGBLIGHT_DEFAULT_VAL 55

#define RGBLIGHT_HUE_STEP 8 // mod 256
#define RGBLIGHT_SAT_STEP 5 // max 255
#define RGBLIGHT_VAL_STEP 5 // max 255

#define RGBLIGHT_EFFECT_BREATHE_MAX 63

#define RGBLIGHT_DEFAULT_MODE (RGBLIGHT_MODE_RAINBOW_MOOD + 2)
